### ISSUE TITLE
CT Duplicate Dependencies

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/proportion-playground#106]
```
proportion-playground : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: duplicate dependencies
Error: Assertion failed: duplicate dependencies
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/assert/js/assert.js:22:13)
    at new DerivedProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/axon/js/DerivedProperty.js?bust=1559120548455:35:17)
    at Function.PaintChoice.getActiveColorProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/model/paint/PaintChoice.js?bust=1559120548455:154:12)
    at new SplotchControl (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/SplotchControl.js?bust=1559120548455:44:19)
    at new PaintSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/PaintSceneNode.js?bust=1559120548455:53:30)
    at new ProportionScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/ProportionScreenView.js?bust=1559120548455:51:7)
    at ExploreScreen.Screen.call.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/explore/ExploreScreen.js?bust=1559120548455:43:34)
    at ExploreScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Screen.js?bust=1559120548455:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559120548455:809:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559120548455:817:27
id: Bayes Chrome
Approximately 5/28/2019, 11:31:07 PM
proportion-playground : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: duplicate dependencies
Error: Assertion failed: duplicate dependencies
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/assert/js/assert.js:22:13)
    at new DerivedProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/axon/js/DerivedProperty.js?bust=1559133357265:35:17)
    at Function.PaintChoice.getActiveColorProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/model/paint/PaintChoice.js?bust=1559133357265:154:12)
    at new SplotchControl (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/SplotchControl.js?bust=1559133357265:44:19)
    at new PaintSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/PaintSceneNode.js?bust=1559133357265:53:30)
    at new ProportionScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/ProportionScreenView.js?bust=1559133357265:51:7)
    at ExploreScreen.Screen.call.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/explore/ExploreScreen.js?bust=1559133357265:43:34)
    at ExploreScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Screen.js?bust=1559133357265:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559133357265:809:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559133357265:817:27
id: Bayes Chrome
Approximately 5/28/2019, 11:31:07 PM
proportion-playground : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: duplicate dependencies
Error: Assertion failed: duplicate dependencies
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/assert/js/assert.js:22:13)
    at new DerivedProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/axon/js/DerivedProperty.js?bust=1559120548455:35:17)
    at Function.PaintChoice.getActiveColorProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/model/paint/PaintChoice.js?bust=1559120548455:154:12)
    at new SplotchControl (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/SplotchControl.js?bust=1559120548455:44:19)
    at new PaintSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/PaintSceneNode.js?bust=1559120548455:53:30)
    at new ProportionScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/ProportionScreenView.js?bust=1559120548455:51:7)
    at ExploreScreen.Screen.call.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/explore/ExploreScreen.js?bust=1559120548455:43:34)
    at ExploreScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Screen.js?bust=1559120548455:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559120548455:809:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559120548455:817:27
id: Bayes Chrome
Approximately 5/28/2019, 11:31:07 PM
proportion-playground : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: duplicate dependencies
Error: Assertion failed: duplicate dependencies
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/assert/js/assert.js:22:13)
    at new DerivedProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/axon/js/DerivedProperty.js?bust=1559133357265:35:17)
    at Function.PaintChoice.getActiveColorProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/model/paint/PaintChoice.js?bust=1559133357265:154:12)
    at new SplotchControl (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/SplotchControl.js?bust=1559133357265:44:19)
    at new PaintSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/PaintSceneNode.js?bust=1559133357265:53:30)
    at new ProportionScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/ProportionScreenView.js?bust=1559133357265:51:7)
    at ExploreScreen.Screen.call.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/explore/ExploreScreen.js?bust=1559133357265:43:34)
    at ExploreScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Screen.js?bust=1559133357265:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559133357265:809:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559133357265:817:27
id: Bayes Chrome
Approximately 5/28/2019, 11:31:07 PM
proportion-playground : fuzz : require.js-canvas : load
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: duplicate dependencies
Error: Assertion failed: duplicate dependencies
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/assert/js/assert.js:22:13)
    at new DerivedProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/axon/js/DerivedProperty.js?bust=1559120247870:35:17)
    at Function.PaintChoice.getActiveColorProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/model/paint/PaintChoice.js?bust=1559120247870:154:12)
    at new SplotchControl (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/SplotchControl.js?bust=1559120247870:44:19)
    at new PaintSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/PaintSceneNode.js?bust=1559120247870:53:30)
    at new ProportionScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/ProportionScreenView.js?bust=1559120247870:51:7)
    at ExploreScreen.Screen.call.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/explore/ExploreScreen.js?bust=1559120247870:43:34)
    at ExploreScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Screen.js?bust=1559120247870:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559120247870:809:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559120247870:817:27
id: Bayes Chrome
Approximately 5/28/2019, 11:31:07 PM
proportion-playground : fuzz : require.js-canvas : load
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: duplicate dependencies
Error: Assertion failed: duplicate dependencies
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/assert/js/assert.js:22:13)
    at new DerivedProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/axon/js/DerivedProperty.js?bust=1559125300499:35:17)
    at Function.PaintChoice.getActiveColorProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/model/paint/PaintChoice.js?bust=1559125300499:154:12)
    at new SplotchControl (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/SplotchControl.js?bust=1559125300499:44:19)
    at new PaintSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/PaintSceneNode.js?bust=1559125300499:53:30)
    at new ProportionScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/ProportionScreenView.js?bust=1559125300499:51:7)
    at ExploreScreen.Screen.call.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/explore/ExploreScreen.js?bust=1559125300499:43:34)
    at ExploreScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Screen.js?bust=1559125300499:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559125300499:809:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559125300499:817:27
id: Bayes Chrome
Approximately 5/28/2019, 11:31:07 PM
proportion-playground : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: duplicate dependencies
Error: Assertion failed: duplicate dependencies
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/assert/js/assert.js:22:13)
    at new DerivedProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/axon/js/DerivedProperty.js?bust=1559120247870:35:17)
    at Function.PaintChoice.getActiveColorProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/model/paint/PaintChoice.js?bust=1559120247870:154:12)
    at new SplotchControl (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/SplotchControl.js?bust=1559120247870:44:19)
    at new PaintSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/PaintSceneNode.js?bust=1559120247870:53:30)
    at new ProportionScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/ProportionScreenView.js?bust=1559120247870:51:7)
    at ExploreScreen.Screen.call.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/explore/ExploreScreen.js?bust=1559120247870:43:34)
    at ExploreScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Screen.js?bust=1559120247870:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559120247870:809:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559120247870:817:27
id: Bayes Chrome
Approximately 5/28/2019, 11:31:07 PM
proportion-playground : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: duplicate dependencies
Error: Assertion failed: duplicate dependencies
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/assert/js/assert.js:22:13)
    at new DerivedProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/axon/js/DerivedProperty.js?bust=1559125300499:35:17)
    at Function.PaintChoice.getActiveColorProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/model/paint/PaintChoice.js?bust=1559125300499:154:12)
    at new SplotchControl (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/SplotchControl.js?bust=1559125300499:44:19)
    at new PaintSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/PaintSceneNode.js?bust=1559125300499:53:30)
    at new ProportionScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/ProportionScreenView.js?bust=1559125300499:51:7)
    at ExploreScreen.Screen.call.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/explore/ExploreScreen.js?bust=1559125300499:43:34)
    at ExploreScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Screen.js?bust=1559125300499:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559125300499:809:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559125300499:817:27
id: Bayes Chrome
Approximately 5/28/2019, 11:31:07 PM
proportion-playground : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: duplicate dependencies
Error: Assertion failed: duplicate dependencies
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/assert/js/assert.js:22:13)
    at new DerivedProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/axon/js/DerivedProperty.js?bust=1559118818908:35:17)
    at Function.PaintChoice.getActiveColorProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/model/paint/PaintChoice.js?bust=1559118818908:154:12)
    at new SplotchControl (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/SplotchControl.js?bust=1559118818908:44:19)
    at new PaintSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/PaintSceneNode.js?bust=1559118818908:53:30)
    at new ProportionScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/ProportionScreenView.js?bust=1559118818908:51:7)
    at ExploreScreen.Screen.call.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/explore/ExploreScreen.js?bust=1559118818908:43:34)
    at ExploreScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Screen.js?bust=1559118818908:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559118818908:809:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559118818908:817:27
id: Bayes Chrome
Approximately 5/28/2019, 11:31:07 PM
proportion-playground : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: duplicate dependencies
Error: Assertion failed: duplicate dependencies
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/assert/js/assert.js:22:13)
    at new DerivedProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/axon/js/DerivedProperty.js?bust=1559123953969:35:17)
    at Function.PaintChoice.getActiveColorProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/model/paint/PaintChoice.js?bust=1559123953969:154:12)
    at new SplotchControl (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/SplotchControl.js?bust=1559123953969:44:19)
    at new PaintSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/PaintSceneNode.js?bust=1559123953969:53:30)
    at new ProportionScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/ProportionScreenView.js?bust=1559123953969:51:7)
    at ExploreScreen.Screen.call.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/explore/ExploreScreen.js?bust=1559123953969:43:34)
    at ExploreScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Screen.js?bust=1559123953969:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559123953969:809:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559123953969:817:27
id: Bayes Chrome
Approximately 5/28/2019, 11:31:07 PM
proportion-playground : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: duplicate dependencies
Error: Assertion failed: duplicate dependencies
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/assert/js/assert.js:22:13)
    at new DerivedProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/axon/js/DerivedProperty.js?bust=1559118818908:35:17)
    at Function.PaintChoice.getActiveColorProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/model/paint/PaintChoice.js?bust=1559118818908:154:12)
    at new SplotchControl (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/SplotchControl.js?bust=1559118818908:44:19)
    at new PaintSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/PaintSceneNode.js?bust=1559118818908:53:30)
    at new ProportionScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/ProportionScreenView.js?bust=1559118818908:51:7)
    at ExploreScreen.Screen.call.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/explore/ExploreScreen.js?bust=1559118818908:43:34)
    at ExploreScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Screen.js?bust=1559118818908:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559118818908:809:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559118818908:817:27
id: Bayes Chrome
Approximately 5/28/2019, 11:31:07 PM
proportion-playground : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: duplicate dependencies
Error: Assertion failed: duplicate dependencies
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/assert/js/assert.js:22:13)
    at new DerivedProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/axon/js/DerivedProperty.js?bust=1559123953969:35:17)
    at Function.PaintChoice.getActiveColorProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/model/paint/PaintChoice.js?bust=1559123953969:154:12)
    at new SplotchControl (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/SplotchControl.js?bust=1559123953969:44:19)
    at new PaintSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/paint/PaintSceneNode.js?bust=1559123953969:53:30)
    at new ProportionScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/common/view/ProportionScreenView.js?bust=1559123953969:51:7)
    at ExploreScreen.Screen.call.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/proportion-playground/js/explore/ExploreScreen.js?bust=1559123953969:43:34)
    at ExploreScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Screen.js?bust=1559123953969:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559123953969:809:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559107867458/joist/js/Sim.js?bust=1559123953969:817:27
id: Bayes Chrome
Approximately 5/28/2019, 11:31:07 PM
```

**Comment by zepumph** [comment]
This will be covered by https://github.com/phetsims/axon/issues/250, closing
